spring:
  config:
    activate:
      on-profile: local
    import: application-secret.yml

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prios_db?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE.CLIENT-ID.local}
            client-secret: ${GOOGLE.CLIENT-SECRET.local}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

claude:
  ai:
    api-key: ${CLAUDE.API-KEY.local}

discord:
  error-alert-url: ${DISCORD.ERROR_ALERT_URL.local}

logging:
  level:
    root: INFO
