spring:
  datasource:
    url: jdbc:mysql://prios-mysql-server.mysql.database.azure.com:3306/prios?useSSL=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    root: info

webclient:
  connect-timeout: 3000
  read-timeout: 5000
